/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RotulosRouteImport } from './routes/rotulos'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RotulosRoute = RotulosRouteImport.update({
  id: '/rotulos',
  path: '/rotulos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/rotulos': typeof RotulosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/rotulos': typeof RotulosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/rotulos': typeof RotulosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historia' | '/rotulos' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historia' | '/rotulos' | '/sitemap.xml'
  id: '__root__' | '/' | '/historia' | '/rotulos' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriaRoute: typeof HistoriaRoute
  RotulosRoute: typeof RotulosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotulos': {
      id: '/rotulos'
      path: '/rotulos'
      fullPath: '/rotulos'
      preLoaderRoute: typeof RotulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriaRoute: HistoriaRoute,
  RotulosRoute: RotulosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
